### ISSUE TITLE
Mailman CGI-BIN

### ISSUE THREAD

**Issue by MHammett** [inex/ixp-manager-docs-md#2]
Should you guys point out that the default mailman install will have ScriptAlias conflicts with the default Apache\PHP7 install?

To get around this, I moved where mailman operates from /cgi-bin/mailman to just /mailman. The mailman.conf Apache site has more information on this, but I spent a while chasing down what was conflicting and how to fix it...  instead of just moving where it operated from and avoiding the conflict altogether.

**Comment by barryo** [comment]
IXP Manager doesn't have any ScriptAlias setting @MHammett - not sure where the conflict exists?

**Comment by MHammett** [comment]
Not directly, no, but Apache, PHP7, and Mailman do. I do understand it isn't a fault of IXP Manager, but it would help those setting up mailman integration.

`[Thu Feb 01 06:37:02.979209 2018] [alias:warn] [pid 287] AH00671: The ScriptAlias directive in /etc/apache2/sites-enabled/mailman.conf at line 4 will probably never match because it overlaps an earlier ScriptAlias.`

`root@ixpm:/srv/ixpmanager# grep -rnw /etc/apache2/ -e 'cgi-bin'
/etc/apache2/conf-available/php7.0-cgi.conf:28:#ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
/etc/apache2/conf-available/php7.0-cgi.conf:29:#<Directory "/usr/lib/cgi-bin">
/etc/apache2/conf-available/php7.0-cgi.conf:35:#Action application/x-httpd-php /cgi-bin/php7.0
/etc/apache2/conf-available/localized-error-pages.conf:9:#ErrorDocument 404 "/cgi-bin/missing_handler.pl"
/etc/apache2/conf-available/serve-cgi-bin.conf:11:              ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
/etc/apache2/conf-available/serve-cgi-bin.conf:12:              <Directory "/usr/lib/cgi-bin">
/etc/apache2/sites-available/default-ssl.conf:21:               #Include conf-available/serve-cgi-bin.conf
/etc/apache2/sites-available/default-ssl.conf:99:               <Directory /usr/lib/cgi-bin>
/etc/apache2/sites-available/mailman.conf:4:ScriptAlias /cgi-bin/mailman/ /usr/lib/cgi-bin/mailman/
/etc/apache2/sites-available/mailman.conf:10:# Use this if you don't want the "cgi-bin" component in your URL:
/etc/apache2/sites-available/mailman.conf:13:#ScriptAlias /mailman/ /usr/lib/cgi-bin/mailman/
/etc/apache2/sites-available/mailman.conf:19:<Directory /usr/lib/cgi-bin/mailman/>
/etc/apache2/sites-available/mailman.conf:57:#ScriptAlias /admin /usr/lib/cgi-bin/mailman/admin
/etc/apache2/sites-available/mailman.conf:58:#ScriptAlias /admindb /usr/lib/cgi-bin/mailman/admindb
/etc/apache2/sites-available/mailman.conf:59:#ScriptAlias /confirm /usr/lib/cgi-bin/mailman/confirm
/etc/apache2/sites-available/mailman.conf:60:#ScriptAlias /create /usr/lib/cgi-bin/mailman/create
/etc/apache2/sites-available/mailman.conf:61:#ScriptAlias /edithtml /usr/lib/cgi-bin/mailman/edithtml
/etc/apache2/sites-available/mailman.conf:62:#ScriptAlias /listinfo /usr/lib/cgi-bin/mailman/listinfo
/etc/apache2/sites-available/mailman.conf:63:#ScriptAlias /options /usr/lib/cgi-bin/mailman/options
/etc/apache2/sites-available/mailman.conf:64:#ScriptAlias /private /usr/lib/cgi-bin/mailman/private
/etc/apache2/sites-available/mailman.conf:65:#ScriptAlias /rmlist /usr/lib/cgi-bin/mailman/rmlist
/etc/apache2/sites-available/mailman.conf:66:#ScriptAlias /roster /usr/lib/cgi-bin/mailman/roster
/etc/apache2/sites-available/mailman.conf:67:#ScriptAlias /subscribe /usr/lib/cgi-bin/mailman/subscribe
/etc/apache2/sites-available/mailman.conf:68:#ScriptAlias /mailman/ /usr/lib/cgi-bin/mailman/`

**Comment by barryo** [comment]
It looks like this is the conflict:

```
/etc/apache2/conf-available/serve-cgi-bin.conf:11: ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
```

So this is a mailman/Apache install issue (on a specific operating system and packages).

To be honest, I'd rather not affect IXP Manager documentation signal-to-noise ratio with non-IXP Manager problems. Hope you understand.

Separately, the reason these APIs exist as web-based APIs is so you can install mailman on a different server to IXP Manager. We'd always recommend separation of functions.

**Comment by MHammett** [comment]
I understand on the not including it part. Maybe this issue existing will be enough for someone's Googling to find it.


Some of us can't spell API.  ;-)

I like APIs, but if there's not a copy, paste, find, replace integration available, I'm probably not going to do it. No time...  hence a year later I'm still working on the mailman integration.  :-) I realize that's just me and that a lot of other people will be able to utilize it.

**Comment by barryo** [comment]
> I like APIs, but if there's not a copy, paste, find, replace integration available, I'm probably not going to do it

This is why the following exists 😉 

> Or the following for the API V4 version (and make sure to update the assignments at the top of the script):
>
> `artisan mailing-list:sync-script`
